name = "LatticeQCD"
uuid = "8a12f9b3-8daf-4285-9aa6-f1d88d857ae8"
authors = ["Akio Tomiya", "Yuki Nagai"]
version = "0.1.1"

[deps]
AlgRemez_jll = "acb6dc63-88f0-54c7-a126-ccdc963b8b3f"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
CLIME_jll = "3c6ae550-c37b-5556-a07e-d40b4910cf1c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Gaugefields = "a461e10c-0d91-493e-bc41-027b226eee91"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LatticeDiracOperators = "019239df-b0e3-486e-8e4c-d1c29ee5d6b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
AlgRemez_jll = "0.1.1"
ArnoldiMethod = "0.2"
Distributions = "0.25"
EzXML = "1"
FastGaussQuadrature = "0.4"
GR = "0.62"
JLD2 = "0.4"
KrylovKit = "0.5"
Plots = "1"
Requires = "1"
SpecialFunctions = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
